---
name: build_image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      output:
        type: string
        default: '/tmp/docker.tar'
      artifact:
        type: string
        required: true
      platform:
        type: string
        default: linux/amd64

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.tag }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          tags: |
            type=ref,event=branch,prefix=gh-
            type=ref,event=pr,prefix=gh-pr-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          platforms: ${{ inputs.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            DOCKER_TAG=${{ steps.meta.outputs.tags }}
            SOURCE_COMMIT=${{ github.sha }}
            SOURCE_BRANCH=${{ github.ref }}
            CI=github
          outputs: type=docker,dest=${{ inputs.output }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.output }}
          retention-days: 1
          if-no-files-found: error
